# Generated by Django 4.1.1 on 2022-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('program', models.CharField(max_length=20)),
            ],
        ),
    ]
